services:
  db:
    container_name: consultant_db
    image: postgres:17
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    container_name: consultant_api
    build:
      context: ../server/api
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - db


volumes:
  db_data:
